sudo: required
services:
  - docker

before_install:
  - docker build -t ajsaavedra/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ajsaavedra/react-test npm test -- --coverage

after_success:
  - docker build -t ajsaavedra/multi-container-client ./client
  - docker build -t ajsaavedra/multi-container-nginx ./nginx
  - docker build -t ajsaavedra/multi-container-server ./server
  - docker build -t ajsaavedra/multi-container-worker ./worker
  #log in to docker cli & push the images to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ajsaavedra/multi-container-client
  - docker push ajsaavedra/multi-container-nginx
  - docker push ajsaavedra/multi-container-server
  - docker push ajsaavedra/multi-container-worker